# Generated by Django 6.0 on 2025-12-23 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200)),
                ('post_content', models.CharField(max_length=5000)),
                ('post_image', models.ImageField(upload_to='post/images')),
                ('post_time', models.DateTimeField()),
                ('post_author', models.CharField(default='unknown User', max_length=100)),
            ],
        ),
    ]
