# Generated by Django 6.0 on 2026-01-19 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.ImageField(upload_to='images/pizzas/')),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('order_received', 'Order Received'), ('preparing', 'Preparing'), ('baking', 'Baking'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered')], default='order_received', max_length=20)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='pizzaservice.pizza')),
            ],
        ),
    ]
