# Generated by Django 6.0 on 2025-12-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.IntegerField(default=0)),
                ('stock_quantity', models.IntegerField(default=1)),
                ('category', models.CharField(choices=[('Electronics', 'Electronics'), ('Tech', 'Tech'), ('Home and appliance', 'Home and appliance'), ('hardware', 'hardware')])),
            ],
        ),
    ]
